### ISSUE TITLE
画面遷移の検討

### ISSUE THREAD

**Issue by datsuns** [white-mmm/todosuke#6]
- 画面は以下のものがある
- 登録画面
- 一覧画面
- 編集画面 (構成は登録画面と同じ)

**Comment by white-mmm** [comment]
考えられるケース書いとく

(1) 登録する場合
一覧画面 → 登録画面 → 一覧画面

(2) 編集する場合
一覧画面 → 編集画面 → 一覧画面

ぐらいかな。
